function [X0, XT] = floquet_fundamental
% Contruir matriz fundamental con los #6 archivos floquet_#.mat
% Salida:
%         X0: matrix fundamental en tiempo 0, 6x6.
%         XT: matrix fundamental en tiempo T, 6x6.

    xx(1) = load("floquet_1.mat");
    xx(2) = load("floquet_2.mat");
    xx(3) = load("floquet_3.mat");
    xx(4) = load("floquet_4.mat");
    xx(5) = load("floquet_5.mat");
    xx(6) = load("floquet_6.mat");

    X0 = [xx(1).x_floq(:,1), ...
          xx(2).x_floq(:,1), ...
          xx(3).x_floq(:,1), ...
          xx(4).x_floq(:,1), ...
          xx(5).x_floq(:,1), ...
          xx(6).x_floq(:,1)]; 

    XT = [xx(1).x_floq(:,2),  ...
          xx(2).x_floq(:,2),  ...
          xx(3).x_floq(:,2),  ...
          xx(4).x_floq(:,2),  ...
          xx(5).x_floq(:,2),  ...
          xx(6).x_floq(:,2)]; 

end